FROM kennarddh/mindustry-server-kotlin-runtime:1.1.3

WORKDIR /app

# Soon genesis is still WIP
# ADD https://github.com/xpdustry/kotlin-runtime/releases/download/v3.1.0-k.1.9.10/kotlin-runtime.jar config/mods/kotlin-runtime.jar

EXPOSE 6567
